/**
 * Payload CMS generated types.
 *
 * These types are generated by running `pnpm generate:types` in apps/cms.
 * After generation, copy the relevant types here to share with the web app.
 *
 * For now, we define the expected shapes manually to unblock frontend development.
 * Once the CMS is running, regenerate with `payload generate:types`.
 */

// ────────────────────────────────────────────────────────────────────────────
// Base types
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
}

export interface PayloadMedia extends PayloadDocument {
  alt: string;
  caption?: string | null;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}

// ────────────────────────────────────────────────────────────────────────────
// Users
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadUser extends PayloadDocument {
  name: string;
  email: string;
  role: 'admin' | 'editor';
}

// ────────────────────────────────────────────────────────────────────────────
// Posts
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadPost extends PayloadDocument {
  title: string;
  slug: string;
  excerpt: string;
  content: unknown; // Lexical rich text JSON
  featuredImage?: PayloadMedia | string | null;
  author: PayloadUser | string;
  tags?: Array<{ tag: string; id?: string }>;
  publishedDate?: string | null;
  status: 'draft' | 'published';
}

// ────────────────────────────────────────────────────────────────────────────
// Pages
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadPage extends PayloadDocument {
  title: string;
  slug: string;
  layoutBlocks?: PayloadBlock[];
}

export type PayloadBlock =
  | PayloadHeroBlock
  | PayloadRichTextBlock
  | PayloadImageBlock
  | PayloadCTABlock;

export interface PayloadHeroBlock {
  blockType: 'hero';
  heading: string;
  subheading?: string | null;
  backgroundImage?: PayloadMedia | string | null;
  primaryCTA?: { label?: string | null; url?: string | null };
  secondaryCTA?: { label?: string | null; url?: string | null };
  id?: string;
}

export interface PayloadRichTextBlock {
  blockType: 'richText';
  content: unknown; // Lexical rich text JSON
  id?: string;
}

export interface PayloadImageBlock {
  blockType: 'image';
  image: PayloadMedia | string;
  caption?: string | null;
  size?: 'full' | 'medium' | 'small';
  id?: string;
}

export interface PayloadCTABlock {
  blockType: 'cta';
  heading: string;
  description?: string | null;
  links?: Array<{
    label: string;
    url: string;
    style?: 'primary' | 'secondary' | 'outline';
    id?: string;
  }>;
  id?: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Events
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadEvent extends PayloadDocument {
  title: string;
  slug: string;
  description: unknown; // Lexical rich text JSON
  date: string;
  time?: string | null;
  location: {
    venue: string;
    address?: string | null;
    city: string;
  };
  coverImage?: PayloadMedia | string | null;
  speakers?: Array<{
    name: string;
    role?: string | null;
    topic?: string | null;
    avatar?: PayloadMedia | string | null;
    twitter?: string | null;
    linkedin?: string | null;
    id?: string;
  }>;
  agenda?: Array<{
    time: string;
    title: string;
    speaker?: string | null;
    id?: string;
  }>;
  tags?: Array<{ tag: string; id?: string }>;
  registrationLink?: string | null;
  status: 'upcoming' | 'past';
}

// ────────────────────────────────────────────────────────────────────────────
// Sponsors
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadSponsor extends PayloadDocument {
  name: string;
  tier: 'gold' | 'silver' | 'bronze' | 'partner';
  logo: PayloadMedia | string;
  url: string;
  description?: string | null;
}

// ────────────────────────────────────────────────────────────────────────────
// Leaders
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadLeader extends PayloadDocument {
  name: string;
  role: string;
  image: PayloadMedia | string;
  bio?: string | null;
  twitter?: string | null;
  linkedin?: string | null;
  github?: string | null;
  sortOrder?: number;
}

// ────────────────────────────────────────────────────────────────────────────
// Gallery Items
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadGalleryItem extends PayloadDocument {
  image: PayloadMedia | string;
  caption: string;
  event?: PayloadEvent | string | null;
  sortOrder?: number;
}

// ────────────────────────────────────────────────────────────────────────────
// Globals
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadHome {
  hero: {
    heading: string;
    subheading?: string | null;
    primaryCTA?: { label?: string | null; url?: string | null };
    secondaryCTA?: { label?: string | null; url?: string | null };
    backgroundVideo?: PayloadMedia | string | null;
  };
  stats?: Array<{ label: string; value: string; id?: string }>;
  featuredProjectsHeading?: string | null;
  sponsorsHeading?: string | null;
  blogHeading?: string | null;
}

export interface PayloadNavigation {
  items: Array<{ label: string; url: string; id?: string }>;
  ctaButton?: { label?: string | null; url?: string | null };
}

export interface PayloadFooter {
  columns?: Array<{
    heading: string;
    links?: Array<{ label: string; url: string; id?: string }>;
    id?: string;
  }>;
  socialLinks?: Array<{
    platform: 'twitter' | 'github' | 'linkedin' | 'youtube' | 'discord';
    url: string;
    id?: string;
  }>;
  nextEventCallout?: {
    enabled?: boolean;
    heading?: string | null;
    description?: string | null;
  };
  copyright?: string | null;
}

export interface PayloadSiteSettings {
  siteName: string;
  siteDescription?: string | null;
  siteUrl?: string | null;
  defaultSEO?: {
    title?: string | null;
    description?: string | null;
    ogImage?: PayloadMedia | string | null;
  };
  contactEmail?: string | null;
  newsletterEndpoint?: string | null;
}

// ────────────────────────────────────────────────────────────────────────────
// API Response types
// ────────────────────────────────────────────────────────────────────────────

export interface PayloadListResponse<T> {
  docs: T[];
  totalDocs: number;
  limit: number;
  totalPages: number;
  page: number;
  pagingCounter: number;
  hasPrevPage: boolean;
  hasNextPage: boolean;
  prevPage: number | null;
  nextPage: number | null;
}
